feat: Add util FolderExists with runnable Example and Unit tests
romie-gr/romie pull request #149
Opened 2020-11-07 17:20 UTC by zoispag

This PRs adds the first filesystem-related utility: `FolderExists`.

Method checks if folder exists and returns a boolean value.
No errors are reported, but logs using logrus, in case `os.IsNotExist` fails.

- has runnable Example
- has unit tests (no mock/abstraction)

2020-11-17 23:59 UTC, ggkioulis approved these changes, later dismissed
looks great to me!

2020-11-18 14:36 UTC, drpaneas reviewed
Thanks for the PR. Lot's of great code here. I have only a few optional suggestions and one thing I didn't understand with `tt := tt`. See my comments ;)

2020-11-18 14:36 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +	} else {
Try to keep the normal code path at minimal indentation, and indent only the error handling part, by dealing with it first. This improves the readability of the code by permitting visually scanning the normal path quickly. For instance:

```go
exists := FolderExists("/a-non-existing-folder")
if !exists {
    fmt.Println("Folder does not exist")
}
fmt.Println("Folder exists")
```

2020-11-18 14:36 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +	_ = AppFS.Mkdir("/a-folder-that-exists", 0755)
since you reuse the strings `"/a-folder-that-exists"` and `"/a-folder-that-exists/file.txt"` it would be better to assign them into variables. Otherwise during refactoring, there is always the risk of forgetting to change these two strings in two different places.

2020-11-18 14:36 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +		tt := tt
what are you trying to achieve with `tt := tt` ?

2020-11-18 14:36 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
Having both _got_ &  _want_ on a single line it's a bit of a downside in a sense that it's hard to see/distinguish them. Maybe something like this:

```go
fmt.Errorf("FolderExists()\ngot:  %v\nwant: %v", got, want)
```

```shell
FolderExists()
got:  false
want: true
```

WDYT?

2020-11-18 14:53 UTC, zoispag commented on internal/utils/filesystem_test.go
> +		tt := tt
Ask our friend, golangci:

![image](https://user-images.githubusercontent.com/21138205/99545886-1f3fe580-29b6-11eb-9512-d8e83792e576.png)

2020-11-18 14:54 UTC, zoispag commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
That's the standard table tests that both VSCode and Goland generate. I have no strong preference.

2020-11-18 14:57 UTC, zoispag commented on internal/utils/filesystem_test.go
> +	} else {
There is no return in this function since it's only used for the example, so in this case, it would print both messages.
I can do:

```go
exists := FolderExists("/a-non-existing-folder")
if !exists {
    fmt.Println("Folder does not exist")
    return
}
fmt.Println("Folder exists")
```

But conceptually it's not the same.

2020-11-18 15:02 UTC, zoispag commented on internal/utils/filesystem_test.go
> +	_ = AppFS.Mkdir("/a-folder-that-exists", 0755)
Done :)

2020-11-18 23:53 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +	} else {
Ah yes, sorry. Coffee issue. Disregard my comment.

2020-11-19 00:29 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +		tt := tt
Ok I did a bit of a research. Seems like Go has a _bug_ in its code. Read carefully the explanation here: https://github.com/golang/go/wiki/CommonMistakes

We could avoid this error by adding this snippet to the `.golangci.yml` configuration:

```shell
issues:
  exclude:
    - Using the variable on range scope .* in function literal
```

However, regardless of my feelings on this irritation -- is actually harmless. From what I understand it's kind of idiomatic to Go language in the same way we explicitly test for `nil`. So I guess we have to start `pin`  variables in loops coming out of `range`. That said, I can't wait for this implementation detail to actually be handled by the language. Until, then we have to use this quirk as constant reminder.

tldr: nothing to change here. I learned something new :D

2020-11-19 00:56 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
Testing frameworks comes with their own report style. Since we do not use any, it's fine. I have no strong preference either.

However, there is another thing I just noticed this one-liner:

```go
if got := FolderExists(tt.path); got != tt.want {
```

I absolutely hate this syntax. If this got generated by the IDE, it's really really bad. It is non-intuitive, and it's not worth saving 2 lines for less readability. It will just confuse people reading the code. For example:

```go
got := FolderExists(tt.path)
if got != tt.want {
  t.Errorf("FolderExists(%q) = %v; want %v", tt.path, got, tt.want)
}
```

2020-11-19 00:58 UTC, drpaneas requested changes
Thanks for the discussion and the effort here. I definitely learned something new (with pin variables) today. I'm fine with all of the choices here but one. I cannot stand the one-liner syntax that GoLand/VSCode generates.

2020-11-19 05:38 UTC, zoispag commented on internal/utils/filesystem_test.go
> +		tt := tt
I was reading about this a while ago. A case with a loop and a goroutine, that was affecting the index. "Shadowing" the local range var implicitly, was the solution to this. 🙂

2020-11-19 05:46 UTC, zoispag commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
I see one big benefit of this one-liner syntax. That you can leverage the scope and use variable only inside this specific line. Go as idiomatic as it is, it offers this syntax (among the undoubtedly small and strict syntax) for a good reason and we could take advantage of it.
I understand the argument, but by reading examples, other people's code and tutorials, everyone will encounter this sooner or later.

I am fine with replacing this, but being part of a generated test setup, I feel it has no special meaning; no more than the actual scenarios we provide to the testing list of structs.

Thoughts?

2020-11-19 10:38 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
I see the value in limiting the scope of the initialisation part. In this specific example there is no issue with it because the variable will still be scoped within `t.Run() {}`; which is absolutely fine. Anyway, this has no special as you say in this testing context, so I'm OK without enforcing this here.

One last question about the `tt` and `tests` names you used; are those as well part of the generated test template by the IDE? If not, I will be in favour of using `testCases` and `tc` (which stands for testcase in QA terminology). For example: https://blog.golang.org/subtests

2020-11-19 10:42 UTC, zoispag commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
Indeed, apart from the actual struct values, the rest is generated by the IDE.

Here's another table-driven test case, generated by [`gotests`](https://github.com/cweill/gotests) using VSCode, from a different project:

```go
func Test_findJob(t *testing.T) {
	type args struct {
		JobID int
	}
	tests := []struct {
		name  string
		args  args
		want  bool
		want1 string
		want2 string
	}{
		{
			name: "missing job",
			args: args{
				JobID: 9999,
			},
			want:  false,
			want1: "",
			want2: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, got1, got2 := findJob(tt.args.JobID)
			if got != tt.want {
				t.Errorf("findJob() got = %v, want %v", got, tt.want)
			}
			if got1 != tt.want1 {
				t.Errorf("findJob() got1 = %v, want %v", got1, tt.want1)
			}
			if got2 != tt.want2 {
				t.Errorf("findJob() got2 = %v, want %v", got2, tt.want2)
			}
		})
	}
}```

2020-11-19 10:47 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +				t.Errorf("FolderExists() = %v, want %v", got, tt.want)
Aha, I see, thanks for the blazing fast reply.

2020-11-19 10:47 UTC, drpaneas requested changes
LGTM
@ggkioulis can you re-review once more?

2020-11-19 10:48 UTC, drpaneas approved these changes

2020-11-19 10:59 UTC, drpaneas submitted a review, later dismissed
@zoispag sorry I missed to mention this among all others.
Can you add the argument to the function `FolderExists()`?

e.g.
```go
// I mean the tt.path with %q
  t.Errorf("FolderExists(%q) = %v; want %v", tt.path, got, tt.want)
```

2020-11-19 11:08 UTC, drpaneas approved these changes
LGTM
Thanks for taking the time to address all of my points. Great work!

2020-11-19 13:16 UTC, ggkioulis approved these changes

2020-11-19 13:16 UTC, merged