feat: Allow configuring debug log level for logrus using env var ROMIE_DEBUG
romie-gr/romie pull request #153
Opened 2020-11-22 12:33 UTC by zoispag

Allow configuring debug log level for logrus using env var ROMIE_DEBUG

Example:

```bash
ROMIE_DEBUG=on go run main.go
```

2020-11-22 13:20 UTC, zoispag commented
@drpaneas golint is awful! 😂😂

2020-11-22 14:46 UTC, drpaneas approved these changes
@ggkioulis I don't get why we need this in that phase, since we do not run `romie` yet. Anyway, just remove the `TODO` so go-lint doesn't break.

2020-11-22 14:46 UTC, drpaneas commented on internal/utils/init.go
> +		// TODO: This is temporary. Remove it once Cobra/Viper is configured, to handle it as a boolean flags
```suggestion
		// See https://github.com/romie-gr/romie/issues/154
```

2020-11-22 14:47 UTC, drpaneas requested changes, later dismissed
I didn't mean to approve the changes :P

2020-11-22 14:49 UTC, drpaneas approved these changes
lgtm

2020-11-22 14:54 UTC, drpaneas commented
ah now it complains for the `init()`. Do you mind if we close this PR and deal with it when cobra is in place?

2020-11-22 14:56 UTC, zoispag commented
> ah now it complains for the `init()`. Do you mind if we close this PR and deal with it when cobra is in place?

I am pretty sure we will need an init sooner or later. I am in favor of disabling this lint rule. WDYT?

2020-11-22 19:38 UTC, drpaneas commented
of course we will, but we will do it through cobra. Let me work on it.

2020-11-23 09:48 UTC, ggkioulis commented on internal/utils/init.go
> +		// TODO: This is temporary. Remove it once Cobra/Viper is configured, to handle it as a boolean flags
When running `go test` it is useful to get the debug messages of the tests that run, at least for me. 
So instead of adding `log.SetLevel(log.DebugLevel)` wherever I might need it ,it is a convenient way to, at least for now, enable debug messages in the entire package, when testing.

2020-11-23 09:48 UTC, ggkioulis approved these changes
lgtm! thanks for the quick implementation

2020-11-23 10:14 UTC, ggkioulis commented
> @ggkioulis I don't get why we need this in that phase, since we do not run `romie` yet. Anyway, just remove the `TODO` so go-lint doesn't break.

When running go test it is useful to get the debug messages of the tests that run, at least for me.
So instead of adding `log.SetLevel(log.DebugLevel)` wherever I might need it ,it is a convenient way to, at least for now, enable debug messages in the entire package, when testing.

2020-11-23 13:52 UTC, drpaneas commented
> When running go test it is useful to get the debug messages of the tests that run, at least for me.

@ggkioulis all test messages are debug messages. You shouldn't replace `*testing.T` with `logrus`. For example you can use `t.log()` and  `t.logf()`.

Unless there is a PR that shows the problem in the code, I am hesitant to enable this.

2020-11-23 13:53 UTC, drpaneas requested changes
See my comments ^

2020-11-23 15:25 UTC, zoispag commented
Superseded by #155

2020-11-23 15:25 UTC, closed without merging

2020-11-23 15:58 UTC, drpaneas commented
> Superseded by #155

I doesn't cover this use case. From what I understood @ggkioulis wants to have debug messages when `go test -v`.
My PR is addressing the case when you run: `romie --debug`.

Again, let's revisit this when there is an actual code example that uses this feature.

2020-11-24 00:39 UTC, drpaneas commented
@ggkioulis  I found this you might can use:

Logrus has a built in facility for asserting the presence of log messages. This is implemented through the test hook and provides:

decorators for existing logger (test.NewLocal and test.NewGlobal) which basically just add the test hook

a test logger (test.NewNullLogger) that just records log messages (and does not output any):

```go

logger, hook := NewNullLogger() logger.Error("Hello error") assert.Equal(1, len(hook.Entries)) assert.Equal(logrus.ErrorLevel, hook.LastEntry().Level) assert.Equal("Hello error", hook.LastEntry().Message) hook.Reset() assert.Nil(hook.LastEntry())
```