feat: create function to check if a one of a series of strings is part of another string
romie-gr/romie pull request #160
Opened 2020-12-05 20:30 UTC by Anastasiadis

Function StringContains checks if a one of a series of strings is part of another string.
closes #140

2020-12-06 12:15 UTC, zoispag commented on internal/utils/string_finder.go
> +	log.Debug("String does not contain arguments")
Imho the debug log is a bit overkill here.

2020-12-06 15:16 UTC, drpaneas requested changes, later dismissed
Awesome @BillAnastasiadis ! Thanks for the work and the PR 👍 

Please see my review comments. Basically I need you to add an additional test to have 100% coverage of your code (right now you have only 90% -- not that it's bad, but it's very easy make it fully tested). My other comments are mostly questions about `TrimSpace` and a few cosmetic things like names of local variables in a range loop.

2020-12-06 15:16 UTC, drpaneas commented on internal/utils/string_finder.go
> +	if strings.TrimSpace(baseString) == "" {
why `TrimSpace()`? Wouldn't `baseString == "" {` work as well?

2020-12-06 15:16 UTC, drpaneas commented on internal/utils/string_finder.go
> +		log.Debug("String is empty")
Since it's a debug message, maybe use the same name of the variable. e.g. `baseString is empty`. It's up to you.

2020-12-06 15:16 UTC, drpaneas commented on internal/utils/string_finder.go
> +	for index, str := range stringlist {
it's quite common in Go to not use abbreviations like `str` nor full names. Consider changing those to:

```go
for i, s := range stringlist {
```

2020-12-06 15:16 UTC, drpaneas commented on internal/utils/string_finder.go
> +		if strings.TrimSpace(str) == "" {
Same here, I don't think `TrimSpace` is necessary.

2020-12-06 15:16 UTC, drpaneas commented on internal/utils/string_finder_test.go
> +		{"String empty search", baseEmpty, []string{""}, false},
You need to add this additional test:

```go
{"String empty search 2", baseString, []string{""}, false},
```

in order to test this part of your code:

```go
if strings.TrimSpace(str) == "" {
			continue
		}
```

because as of now, your tests are not touching this.

TIP: You can always run `make cover`. This will open your browser and your can select your test file. It will show you with green color the lines your test is covering and with red the lines which are not.

2020-12-26 22:55 UTC, Anastasiadis commented on internal/utils/string_finder.go
> +		log.Debug("String is empty")
Thanks for the feedback. Changed it to "Input string" to make it clear even without code context.

2020-12-26 22:55 UTC, Anastasiadis commented on internal/utils/string_finder.go
> +	for index, str := range stringlist {
Done!

2020-12-26 22:56 UTC, Anastasiadis commented on internal/utils/string_finder.go
> +	if strings.TrimSpace(baseString) == "" {
In case the base string is not empty but an arbirtary amount of whitespace. 
i.e. _"" != "  " != "        "_.

2020-12-26 22:58 UTC, Anastasiadis commented on internal/utils/string_finder_test.go
> +		{"String empty search", baseEmpty, []string{""}, false},
Added!

2020-12-27 12:04 UTC, drpaneas reviewed
LGTM

2020-12-27 12:05 UTC, drpaneas approved these changes

2020-12-27 12:06 UTC, zoispag approved these changes
LGTM 💪

2020-12-27 12:12 UTC, merged