fix: FileExists panics w/o read permission
romie-gr/romie pull request #172
Opened 2020-12-29 04:38 UTC by drpaneas

Add permission check

Fixes #171

2020-12-29 08:30 UTC, zoispag approved these changes

2020-12-29 08:35 UTC, zoispag requested changes, later dismissed
Are you sure the second test case fails for the correct reason? Looks to me that it fails because file does not exist, not because of permissions.

2020-12-29 15:26 UTC, drpaneas commented
> Are you sure the second test case fails for the correct reason? Looks to me that it fails because file does not exist, not because of permissions.

yes, in both cases it through a segfault and crashes.

2020-12-29 15:57 UTC, zoispag commented on internal/utils/filesystem_test.go
> +		},
Isn't this scenario redundant?

2020-12-29 17:14 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +		},
it triggers the part of the code where parent dir doesn't exist, so it has to create it. Otherwise you end up with 90% test coverage.

2020-12-29 21:54 UTC, zoispag commented on internal/utils/filesystem_test.go
> +		},
I don't get that. Do you mean as part of the CreateFile method? Because the `exists` method does not differentiate between files and directories. If the path does not exist, it will "fail".

2020-12-29 21:56 UTC, zoispag commented on internal/utils/filesystem_test.go
> +		},
For the sake of argument, I tried to split the 2 checks into 2 if statements.

```go
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false
		}

		if os.IsPermission(err) {
			return false
		}
	}
```

I get 100% coverage without the scenario: `Returns false when given file and its parent folder do not exist`

2020-12-29 23:31 UTC, drpaneas commented on internal/utils/filesystem_test.go
> +		},
Sorry my bad. I got confused between `file.go` and `filesystem.go`. This is obviously redundant, thanks for catching it.

2020-12-29 23:59 UTC, zoispag approved these changes

2020-12-30 00:10 UTC, ggkioulis commented on internal/utils/filesystem_test.go
> +
Does it make sense to `defer` here the `os.RemoveAll(nonWritableDir)` for visibility?

2020-12-30 00:11 UTC, zoispag approved these changes

2020-12-30 00:14 UTC, ggkioulis approved these changes

2020-12-30 00:15 UTC, zoispag commented on internal/utils/filesystem_test.go
> +
Hm. I like this idea. I didn't think about that, when I added the cleanup call to the ExtractTo test case. Defer being idiomatic go and not something I am used to it yet!
, I usually forget about it! 😇

2020-12-30 00:21 UTC, merged