WIP: Add html fetching utility
romie-gr/romie pull request #180
Opened 2021-01-31 11:52 UTC by Anastasiadis

Adds the GetHTMLObj function, which returns the goquery HTML Document of any user defined url.

2021-02-01 17:24 UTC, drpaneas commented on internal/utils/html_fetcher.go
> +//GetHTMLObj returns the HTML document for a user provided url
`GetHTML` is a better name

2021-02-14 11:44 UTC, Anastasiadis commented on internal/utils/html_fetcher.go
> +//GetHTMLObj returns the HTML document for a user provided url
Changed final commit!

2021-02-14 12:28 UTC, zoispag requested changes, later dismissed
Please see some comments

2021-02-14 12:28 UTC, zoispag commented on internal/utils/html_fetcher.go
> +	}
What about the rest of the 2xx HTTP status codes?
Why a 201, `http.StatusCreated`, is not an accepted one?

2021-02-14 12:28 UTC, zoispag commented on internal/utils/html_fetcher_test.go
> +		case "a":
Can we be a bit more specific with these "named" mock server cases?

2021-02-14 12:28 UTC, zoispag commented on internal/utils/html_fetcher_test.go
> +			"OK",
Your scenario name must be descriptive, like a natural language sentence. 
eg: It can download an HTML object when the HTTP status code is 200.

2021-02-14 12:28 UTC, zoispag commented on internal/utils/html_fetcher.go
> +		return nil, fmt.Errorf("goquery is unable to parse the returned html")
```suggestion
		return nil, fmt.Errorf("Error loading HTTP response body (%v)", err)
```

2021-02-21 09:22 UTC, Anastasiadis commented on internal/utils/html_fetcher.go
> +		return nil, fmt.Errorf("goquery is unable to parse the returned html")
Fixed all in last commit!

2021-02-28 12:38 UTC, drpaneas requested changes
Please fix this the CI error, so we can merge this.

2021-02-28 12:38 UTC, drpaneas commented on internal/utils/html_fetcher_test.go
> +func MockServer(testCase string) *httptest.Server {
```suggestion
func mockServer(testCase string) *httptest.Server {
```

I don't see why you need to export this (e.g. UpperCase).

2021-02-28 12:38 UTC, drpaneas commented on internal/utils/html_fetcher.go
> +	res, err := http.Get(url)
According to best practices it's always good to create a context and pass it. This is why the CI is currently failing.
https://search.gocenter.io/github.com/sonatard/noctx

Please fix this, so we can merge.

2021-07-28 20:10 UTC, closed without merging