Initial Makefile
romie-gr/romie pull request #54
Opened 2020-10-01 23:53 UTC by ktsamis

Initial Makefile

I know $(GOCMD) is longer than go but not sure which one to keep. 
We definitely need to talk about the logic of a lot of these targets. There are some that are useless, some that make no sense and some that are just duplicated in logic. This is a first draft of what I have that produces some actual output.

2020-10-01 23:58 UTC, ktsamis commented
Should fix #33 when it's done.

2020-10-02 00:18 UTC, drpaneas commented on go.mod
> +require (
Are those generated by running `go mod tidy` or did you manually wrote them and _then_ run `go mod tidy`?

2020-10-02 00:24 UTC, drpaneas commented
@Anastasiadis @cerebrux please review

2020-10-04 14:00 UTC, drpaneas requested changes
Great work @ktsamis :love_you_gesture: :metal: :clap:

:point_right: I have made suggestion for each part, please take them into consideration. Here's a quick summary:

- you don't need to `go get` the stuff since after this PR will be part of the `go.mod` and `go.sum`. -Given you run `go mod download` at the beginning, then everything you need will be fetched as well.
- I made suggestions for `test` and `cover`. I think it's better to use the browser view, it's way clearer.
- the `todo` target is failing for me.
- for `golangci` you need a configuration file. I added my suggestion, feel free to use it.

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +TIMEOUT=300
```suggestion
GOCMD=LC_ALL=C go
TIMEOUT=5
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +TIMEOUT=300
Also export those:

```shell
export GO111MODULE := on
export GOPROXY = https://proxy.golang.org,direct
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +## all: Default target, now is build setup fmt test cover lint ci clean todo run help
```suggestion
## all: Default target, now is build
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@$(GOCMD)fmt -d ${SRC}
```suggestion
## fmt: Runs go goimports and go fmt
fmt: setup
	@$(GOCMD)imports -w ${SRC}
	@$(GOCMD)fmt -w -s ${SRC}
```

There's no need to run `go get` it because after this PR, this would be part of the `go.mod` -- suffice to run `go mod download` is called as a prereq

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@$(GOCMD) test -cover -v > coverage.txt -timeout $(TIMEOUT)s
```suggestion
	@$(GOCMD) test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -run . -timeout $(TIMEOUT)m
```

I changed my mind about generating a `coverage.txt` with the output result. It's way better to just print the results to the `stdout` (which is the default use-case) and then generate a `coverage.txt` which will be used to view it via browser.

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@cat coverage.txt
```suggestion
## cover: Runs all tests and opens the coverage report in the browser
cover: test
	@$(GOCMD) tool cover -html=coverage.txt
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@misspell .
```suggestion
## lint: Runs golangci-lint (configuration at: .golangci.yml) and misspell 
lint: setup
	@echo Set up the linters now running
	@golangci-lint run --max-issues-per-linter 0 --max-same-issues 0 ./...
	@misspell ./...
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +ci: test fmt lint
Let's add `build` into this:

```suggestion
## ci: Runs build, test, fmt, lint
ci: build test fmt lint 
```

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@grep -I -R -n TODO * --exclude=Makefile
This is failing for me with `Exit code 2`.

2020-10-04 14:00 UTC, drpaneas commented on Makefile
> +	@misspell .
Create `.golangci.yml` and put this configuration:

```yaml
# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  tests: true

linters:
  enable-all: true
  disable:
    - gomnd
    - gocognit
    - goerr113
    - gofumpt
    - gci
    - nlreturn
```

2020-10-05 09:07 UTC, drpaneas commented
@ktsamis I found a better way of handling the `go get`. Please read: https://github.com/go-modules-by-example/index/blob/master/010_tools/README.md

Actually it was part of https://github.com/drpaneas/romie/issues/20

2020-10-08 06:51 UTC, drpaneas commented on Makefile
> +TIMEOUT=300
You forgot to export those. I will do it ;)

2020-10-08 06:53 UTC, drpaneas commented on Makefile
> +	@misspell .
You forgot to create this file.

2020-10-08 08:19 UTC, drpaneas submitted a review, later dismissed
lgtm

2020-10-08 09:24 UTC, cerebrux approved these changes, later dismissed
/LGTM

2020-10-08 10:19 UTC, ggkioulis commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
This expression gives `/bin/sh: ${PWD\#\#*/}: bad substitution` when running make, and results in TARGET being empty

2020-10-08 12:40 UTC, drpaneas commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
It works fine for me:

```shell
[drpaneas@pgeorgia-mac romie (makefile)]$ make build
Building...
[drpaneas@pgeorgia-mac romie (makefile)]$ make run
Building...
Hello romie
```

```shell
$ make -n run
echo "Building..."
LC_ALL=C go build -o romie
LC_ALL=C go run romie
```

Can you provide a reproducer?

2020-10-08 12:53 UTC, drpaneas commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
@ggkioulis can you test if `TARGET := $(shell echo $${PWD-`pwd`})` works for you?

2020-10-08 12:59 UTC, ggkioulis commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
Env:
```
cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20200930"

rpm -q make
make-4.3-2.20.x86_64
```

Steps to fail:
```
geor@arnor:~/github/romie(makefile)$ make run
/bin/sh: ${PWD\#\#*/}: bad substitution
Building...
go run: no go files listed
make: *** [Makefile:71: run] Error 1
```

Dry run:
```
geor@arnor:~/github/romie(makefile)$ make -n run
/bin/sh: ${PWD\#\#*/}: bad substitution
echo "Building..."
LC_ALL=C go build -o romie
LC_ALL=C go run 
```

2020-10-08 13:02 UTC, drpaneas commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
See my comment https://github.com/drpaneas/romie/pull/54#discussion_r501696129

2020-10-08 13:03 UTC, ggkioulis commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
> @ggkioulis can you test if https://pastebin.com/raw/iQ8bcuy3 works for you?

Runs great!

2020-10-08 13:07 UTC, drpaneas commented on Makefile
> +TARGET := $(shell echo $${PWD\#\#*/})
Ah I see the problem. I can also reproduce it with `gmake`.

2020-10-08 13:10 UTC, drpaneas approved these changes

2020-10-08 13:14 UTC, cerebrux commented on Makefile
> +	@grep -I -R -n TODO * --exclude=Makefile
is this still failing to you ? If not click "resolve conversation"

2020-10-08 13:35 UTC, ggkioulis approved these changes

2020-10-08 13:38 UTC, cerebrux approved these changes

2020-10-08 13:39 UTC, merged

2020-10-10 21:52 UTC, ktsamis commented
Sorry for not reviewing the changes earlier. I'm glad it worked out :)