Build multi-platform bins for Linux, Mac Windows
romie-gr/romie pull request #67
Opened 2020-10-09 12:40 UTC by cerebrux

- Added missing "popular" BSD OSes (dragonfly and netbsd)
- Added arm6 and arm7 binaries
- Added modified timestamp on the output binary to ensure a build was reproducible (see: https://goreleaser.com/customization/build/)
- Added ignore section, for architecture that are not supported by Go in
combination with the $goos (see https://golang.org/doc/install/source#environment)

Fixes #13

2020-10-09 12:47 UTC, cerebrux commented
And as usual my test **https://github.com/cerebrux/romie/releases/tag/0.0.1**

2020-10-10 13:25 UTC, drpaneas commented
@GrSoul  was working on https://github.com/drpaneas/romie/issues/15
@cerebrux is this covered already by your PR?

2020-10-10 13:40 UTC, drpaneas requested changes
Add the information that fixes `15 issue` as well.

2020-10-10 13:40 UTC, drpaneas commented on .goreleaser.yml
> +    mod_timestamp: "{{ .CommitTimestamp }}"
This line `fixes #15` as well. Please add that into your in your commit msg.

e.g. `git commit --amend`.

2020-10-10 14:11 UTC, cerebrux commented on .goreleaser.yml
> +    mod_timestamp: "{{ .CommitTimestamp }}"
Done. Number 3 in my comment describes the commit. Also added that it fixes #15

2020-10-11 06:40 UTC, drpaneas approved these changes

2020-10-11 08:13 UTC, zoispag approved these changes
Changes make sense. Good call on the ignore list for valid combinations.

2020-10-11 08:22 UTC, merged