👷 ci: Add action to automate go mod tidy
romie-gr/romie pull request #74
Opened 2020-10-11 16:12 UTC by zoispag

👷 ci: Add action to automate go mod tidy

- Uses `futuratrepadeira/changed-files@v3.2.1` action to check for updates on `go.mod`, `go.sum` or `.github/workflows/go-mod-tidy.yml`
- Conditionally uses `sue445/go-mod-tidy-pr@master` to run `go mod tidy` and create a PR

Closes #7

> `workflow_dispatch` is temp as part of WIP to test the action

2020-10-11 16:31 UTC, zoispag commented
@drpaneas if `sue445/go-mod-tidy-pr@master` is working the way it is supposed to work, then I am guessing that token provided via `secrets.GITHUB_TOKEN` does not have the proper scope to create PRs, even though the branch is created and pushed to remote.

![image](https://user-images.githubusercontent.com/21138205/95684156-deeb8b80-0bef-11eb-8643-9b8dad82c26b.png)

![image](https://user-images.githubusercontent.com/21138205/95684163-eca11100-0bef-11eb-9655-2fdd1935df1a.png)

I'll need your help here.

2020-10-11 16:41 UTC, zoispag commented
Update: After doing some research, it looks like `secrets.GITHUB_TOKEN` is more than enough to create PRs, but will not do so, if triggered by another PR, to avoid an endless loop situation.
That being said, I will then revert `go.mod` changes and remove the `pull_request` event, to make the PR ready for merge.

2020-10-15 12:12 UTC, drpaneas commented
Can you squash the commits?

2020-10-15 12:36 UTC, zoispag commented
> Can you squash the commits?

@drpaneas  aren't you going to do Squash and Merge from the PR?

2020-10-15 13:14 UTC, drpaneas commented
> > Can you squash the commits?
> 
> @drpaneas aren't you going to do Squash and Merge from the PR?

coffee ... I need ...

2020-10-15 13:15 UTC, drpaneas approved these changes

2020-10-15 13:16 UTC, zoispag commented
> coffee ... I need ...

![](https://media.giphy.com/media/l2JI4zgwXw5IfyssE/giphy.gif)

2020-10-21 13:42 UTC, cerebrux requested changes

2020-10-21 13:42 UTC, cerebrux commented on .github/workflows/go-mod-tidy.yml
> +          git_user_email: github-actions@example.com
is this mail legit ? :P

2020-10-21 13:43 UTC, zoispag commented on .github/workflows/go-mod-tidy.yml
> +          git_user_email: github-actions@example.com
Yeap. As long as it's a valid email address, git is supposed to accept a commit.

2020-10-21 13:45 UTC, cerebrux commented on .github/workflows/go-mod-tidy.yml
> +          git_user_email: github-actions@example.com
I thought it should be @drpaneas (project owner) email :)

2020-10-21 13:47 UTC, zoispag commented on .github/workflows/go-mod-tidy.yml
> +          git_user_email: github-actions@example.com
I don't think a real maintainer should make arbitrary automated commits issued by bots.

2020-10-21 13:47 UTC, zoispag commented on .github/workflows/go-mod-tidy.yml
> +          git_user_email: github-actions@example.com
It needs to be clear that the commit was actually originated by a **_bot_** account.

2020-10-21 13:49 UTC, cerebrux approved these changes

2020-10-21 13:49 UTC, merged