ci: Build and publish container image
romie-gr/romie pull request #80
Opened 2020-10-16 11:07 UTC by ggkioulis

* Builds container images using goreleaser docker

* Images built are :latest and :tag

* Images are pusblished to docker.io

* Build is triggered when a tag is pushed

2020-10-16 11:09 UTC, ggkioulis commented
We should decide on which account the images should be published on dockerhub.

2020-10-16 11:31 UTC, ggkioulis commented
> We should decide on which account the images should be published on dockerhub.

So, I created a new account, `romie`

2020-10-18 12:14 UTC, cerebrux submitted a review, later dismissed
LGTM

2020-10-18 12:16 UTC, zoispag requested changes
I actually want to discuss this one first. I don't think a Dockerfile that just copies an executable created by goreleaser is all we want.

2020-10-18 12:44 UTC, ggkioulis commented
> I actually want to discuss this one first. I don't think a Dockerfile that just copies an executable created by goreleaser is all we want.

Well of course once the apo grows we will adapt the Dockerfike. For now that romie just builds a binary as a proof of concept I think it makes sense,l

2020-10-19 00:15 UTC, drpaneas requested changes
Thanks @ggkioulis for the work. Please remove *all* the comments from the goreleaser configuration and then we can merge it.

@zoispag thanks for bringing this up to the stand-up. Just to fill @ggkioulis into the details: we discussed the possibility of building `romie` inside a container. For example:

```shell
make build-in-container
# this will start an ephemeral container mounting the pwd
# install the build dependencies
# run make build
# export the binary to the host system
```

This dockerfile is just for releasing the binary. The official way of building the binary is via go-releaser that is happening into GH Actions.

We could add a secondary dockerfile, providing an alternative way of building (for dev purposes), but in another PR.

2020-10-20 22:07 UTC, drpaneas approved these changes
Thanks for the work ;)

2020-10-20 22:35 UTC, zoispag approved these changes

2020-10-27 19:14 UTC, merged