[WIP] Documentation using Mkdocs
romie-gr/romie pull request #81
Opened 2020-10-20 18:13 UTC by JohnGavr

Added
- Docs destination path as #34 
- GH Action for the publish docs
- Makefile serve option as #32 

Tested and works.

The stage of the PR is **WIP** because we must edit the md files. In some meeting we can discuss about the structure of the page.

Thanks to @zoispag for his help.

2020-10-20 22:28 UTC, drpaneas requested changes, later dismissed
Great team work folks 💯 
Please see my comments.

2020-10-20 22:28 UTC, drpaneas commented on www/docs/index.md
> +Rom scraper for emulatorgames.net
we are not yet settled on the host yet. Most probably it would be the archive roms I sent the other day to the chat.

2020-10-20 22:28 UTC, drpaneas commented on Makefile
> +
You need to also add the `server` at:

```
- .PHONY: all build setup fmt test cover lint clean todo run help
+ .PHONY: all build setup fmt test cover lint clean todo run serve help
```

2020-10-20 22:28 UTC, drpaneas commented on www/mkdocs.yml
> +repo_url: https://github.com/drpaneas/romie
Until we get a domain, use: `https://drpaneas.github.io/romie/` for the `repo_url`.

2020-10-20 22:33 UTC, zoispag commented on www/docs/index.md
> +Rom scraper for emulatorgames.net
We just used the README 😋

2020-10-21 07:52 UTC, JohnGavr commented on www/mkdocs.yml
> +repo_url: https://github.com/drpaneas/romie
Maybe you mean `site_url`?

2020-10-21 07:54 UTC, zoispag commented on www/mkdocs.yml
> +site_url: https://romie.com
```suggestion
site_url: https://drpaneas.github.io/romie/
```

2020-10-21 07:58 UTC, zoispag commented on .github/workflows/publish_docs.yml
> +          mkdocs gh-deploy --force
`insert_final_newline = true` 😊

```suggestion
          mkdocs gh-deploy --force

```

2020-10-24 12:45 UTC, zoispag commented
pinging @drpaneas 
In the original description in #32 you said that you wanted the docs to be inside a `www` dir.

gh-pages look like they assume that docs reside in a `docs` dir in repo root.

![image](https://user-images.githubusercontent.com/21138205/97082105-7ea11480-1607-11eb-8194-26c9b36b284f.png)

Should we change it?

2020-11-19 01:03 UTC, drpaneas commented
> pinging @drpaneas
> In the original description in #32 you said that you wanted the docs to be inside a `www` dir.
> 
> gh-pages look like they assume that docs reside in a `docs` dir in repo root.
> 
> ![image](https://user-images.githubusercontent.com/21138205/97082105-7ea11480-1607-11eb-8194-26c9b36b284f.png)
> 
> Should we change it?

Sorry I missed that. Yes please, change it to `docs`.

2020-11-19 16:02 UTC, zoispag approved these changes

2020-11-19 16:02 UTC, zoispag commented
@drpaneas your turn :)

2020-11-20 12:10 UTC, ktsamis approved these changes
Looks good, let's merge :100:

2020-11-20 12:16 UTC, merged